### ISSUE TITLE
Show Michelson script

### ISSUE THREAD

**Issue by rafoo** [baking-bad/better-call-dev#137]
While I often find better-call.dev's extension to Michelson convenient for reading, I would like to be able to obtain the script in a form suitable for `tezos-client` so that I can easily originate the same script or play with it locally. Would it be possible to have an option to turn the extension off and read the actual Michelson script of the contract?

This is similar but slightly different from #64.

**Comment by m-kus** [comment]
Sure, we plan to add this feature to the next major release of BCD2. Stay tuned :)
