### ISSUE TITLE
misdisplayed timestamp 

### ISSUE THREAD

**Issue by jaiyalas** [baking-bad/better-call-dev#23]
I noticed that, on better-call-dev, _timestamp_ will be displayed like: 

![image](https://user-images.githubusercontent.com/10867/58233902-dc289600-7d6f-11e9-922c-40e599f3a724.png)

But it's not correct and on TzScan it looks like this:

![image](https://user-images.githubusercontent.com/10867/58233918-e64a9480-7d6f-11e9-9624-856fb300515f.png)

**Comment by RomanSerikov** [comment]
Hi @jaiyalas! Looks like problem is solved now. Check it out

**Comment by jaiyalas** [comment]
looks perfect! 👍
