### ISSUE TITLE
Handle non-standard error ids

### ISSUE THREAD

**Issue by m-kus** [baking-bad/better-call-dev#47]
https://better-call.dev/#alpha:KT1QtrYkPtgXBqeVG8K7wo3uQErZpo44W9Sv

Error id example:
proto.Pt24m4xiPbLDhVgVfABUjirbmda3yohdN82Sp9FeuAXJ4eV9otd.michelson_v1.runtime_error

**Comment by RomanSerikov** [comment]
already resolved
