### ISSUE TITLE
Add sandboxing mode 

### ISSUE THREAD

**Issue by m-kus** [baking-bad/better-call-dev#5]
1. Add localnet option (rpc node address 127.0.0.1)
2. Handle net switch in query string
3. Iterate over all blocks instead of querying transactions for account

Take script and storage from https://alphanet-node.tzscan.io/chains/main/blocks/head/context/contracts/KT1XtauF2tnmAKBzbLA2gNoMji9zSzSyYq9w
Then iterate from head to genesis https://alphanet-node.tzscan.io/chains/main/blocks/head~1, ~2, ~3, ...

**Comment by RomanSerikov** [comment]
done
