### ISSUE TITLE
Add meta description

### ISSUE THREAD

**Issue by m-kus** [baking-bad/better-call-dev#55]
![Screenshot from 2019-07-12 20-00-29](https://user-images.githubusercontent.com/44951260/61145326-d33a8200-a4df-11e9-9927-a0f42bfd17c1.png)

**Comment by RomanSerikov** [comment]
<img width="548" alt="Screen Shot 2019-09-30 at 18 01 02" src="https://user-images.githubusercontent.com/11049859/65890900-5a471a00-e3ac-11e9-8a43-c4ff091fcef5.png">
